---
##############################################
# AKS Configuration
##############################################

# aks private cluster
workload_aks: 1
workload_app_aks_subnet_key: "workload_app_aks_subnet"
workload_aks_name: "workload-aks"
workload_aks_dns_prefix: "aks-private"
workload_aks_kubernetes_version: "1.28.3"
workload_aks_private_cluster_enabled: "true"
#workload_aks_enable_rbac: "true"
#workload_aks_oidc_issuer_enabled: "true"
#workload_aks_workload_identity_enabled: "true"
#workload_aks_private_cluster_public_fqdn_enabled: "true"
workload_aks_default_node_pool_name: "default"
workload_aks_default_node_pool_node_count: "1"
workload_aks_default_node_pool_vm_size: "Standard_D2_v2"
workload_aks_network_profile_network_plugin: "azure"
#workload_aks_network_profile_network_plugin_mode: "overlay" # when network_plugin_mode is set to overlay, the network_plugin field can only be set to azure. When upgrading from Azure CNI without overlay, pod_subnet_id must be specified.
workload_aks_network_profile_outbound_type: "userDefinedRouting"
workload_aks_network_profile_load_balancer_sku: "standard"
workload_aks_network_profile_dns_service_ip: "10.41.0.10"
workload_aks_network_profile_service_cidr: "10.41.0.0/24"
#workload_aks_network_profile_pod_cidr: "8.244.0.0/16"

# node pools
workload_aks_node_pools: 1
workload_aks_private_cluster_user_node_pool_name: "user"
workload_app_aks_user_node_pool_subnet_key: "workload_app_aks_user_node_pool_subnet"
workload_aks_private_cluster_user_node_pool_node_count: 1 
workload_aks_private_cluster_user_node_pool_vm_size: "Standard_D2_v2"