---
- hosts: localhost
  tasks:
    - name: Load config
      include_vars: landing-zone-config.yml
    - name: Render config for landing zone
      template:
        src: "landing-zone-template.j2"
        dest: "../generated-landing-zone.tfvars"