---
- hosts: localhost
  tasks:
    - name: Load config
      include_vars:
        dir: vars  
        extensions:
          - yml   
    - name: Render config for landing zone
      template:
        src: "landing-zone-template.j2"
        dest: "../generated-landing-zone.tfvars"